//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanedBudgetPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Childf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Childf()
        {
            this.Customerdfs = new HashSet<Customerdf>();
            this.Customerfs = new HashSet<Customerf>();
            this.Customerfms = new HashSet<Customerfm>();
        }
    
        public string ChildId { get; set; }
        public string ChildName { get; set; }
        public string ParentId { get; set; }
    
        public virtual Parentf Parentf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customerdf> Customerdfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customerf> Customerfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customerfm> Customerfms { get; set; }
    }
}
