//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanedBudgetPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopEntities : DbContext
    {
        public OnlineShopEntities()
            : base("name=OnlineShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChartOfAccount> ChartOfAccounts { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Childf> Childfs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customerd> Customerds { get; set; }
        public virtual DbSet<Customerdf> Customerdfs { get; set; }
        public virtual DbSet<Customerf> Customerfs { get; set; }
        public virtual DbSet<Customerfm> Customerfms { get; set; }
        public virtual DbSet<Customerm> Customerms { get; set; }
        public virtual DbSet<FisicalYear> FisicalYears { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Orderd> Orderds { get; set; }
        public virtual DbSet<Orderfd> Orderfds { get; set; }
        public virtual DbSet<Orderfm> Orderfms { get; set; }
        public virtual DbSet<Orderf> Orderfs { get; set; }
        public virtual DbSet<Orderm> Orderms { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Parentf> Parentfs { get; set; }
        public virtual DbSet<RevenueCategory> RevenueCategories { get; set; }
        public virtual DbSet<ChartOfAccountf> ChartOfAccountfs { get; set; }
    }
}
