//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanedBudgetPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderd
    {
        public System.Guid OrderId { get; set; }
        public System.Guid CustomerId { get; set; }
        public string RevenueCategoryId { get; set; }
        public decimal Amountyplan { get; set; }
        public decimal Amountyperformance { get; set; }
        public int Id { get; set; }
    
        public virtual Customerd Customerd { get; set; }
        public virtual RevenueCategory RevenueCategory { get; set; }
    }
}
